src/org/pentaho/mongo/wrapper/UsernamePasswordMongoClientWrapper.java
information when Authentication is used in MongoDB
What was done:
1) resolved double authentication issue with 2.13 driver
2) resolved db selection issue. Empty DB is no longer allowed for
authentication, so default admin db is used
=> PDI-13500 -- MongoDB Input "GetDBs" option fails to fetch database

build.properties
PDI.
What was done:
1) changed driver version in property files
=> BACKLOG-2583 -- Upgrade to MongoDB Driver 2.13 for the MongoDB plugin -

src/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputData.java, src/org/pentaho/mongo/wrapper/collection/DefaultMongoCollectionWrapper.java, src/org/pentaho/mongo/wrapper/collection/MongoCollectionWrapper.java, test-src/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDataTest.java
Supply the user-specified options to MongoDB when creating an index
=> [PDI-13939] MongoDB Index Creation Options

pom.xml, src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputData.java, src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java, src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/models/MongoDbModel.java, src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputDataTest.java
* Changed dependecy for swt.* packages to optional (in case these bundles are trying to start on cluster without UI)
* Moved ui discoverFields metods into dialog classes.
=> [BACKLOG-5864] - REG: PMR: Reducer fails on the client due to job running.

src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java
- environmentSubstitute for username and password was added.
=> [PDI-14881] MongoDB Input step does not accept username/password environment variables

src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java
- environmentSubstitute for username and password was added.
=> [SP-2491] Backport of PDI-14881 - MongoDB Input step does not accept username/password environment variables (6.0 Suite)

src/main/java/org/pentaho/di/trans/steps/mongodb/MongoDbMeta.java, src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java, src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java, src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMeta.java, src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java, src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/models/MongoDbModel.java, src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java, src/main/resources/org/pentaho/di/trans/steps/mongodbinput/messages/messages_en_US.properties, src/main/resources/org/pentaho/di/trans/steps/mongodboutput/messages/messages_en_US.properties
- AuthenticationDatabase property is added to Meta
- AuthenticationDatabase field are added to MongoDbInput and MongoDbOutput steps
- AuthenticationDatabase field labels are added to messages bundle for i18n
=> [PDI-12725] Support MongoDB AuthenticationDatabase Parameter in MongoDB Steps

src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputXulDialog.java, src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/models/MongoDbModel.java, src/main/resources/org/pentaho/di/ui/trans/steps/mongodbinput/xul/mongodb_input.properties, src/main/resources/org/pentaho/di/ui/trans/steps/mongodbinput/xul/mongodb_input.xul
- Authentication Database field is added to MongoDdInputXulDialog
=> [PRD-5601] Getting Collections in PRD and MongoDB as a datasource, with authentication, stopped working

pom.xml
Import-Package header needs packages ',' separated and package properties ';' separated
@brosander
=> [PDI-15038]Malformed Bundle Manifest

src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java, src/test/java/org/pentaho/mongo/wrapper/MongoWrapperUtilTest.java
- added connection timeout and socket timeout environment variables substitution
- added unit test
=> [PDI-14643] mongoDB input does not accept variables

src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java, src/test/java/org/pentaho/mongo/wrapper/MongoWrapperUtilTest.java
- added connection timeout and socket timeout environment variables substitution
- added unit test
=> [SP-3170][PDI-14643] mongoDB input does not accept variables

src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java, src/test/java/org/pentaho/mongo/wrapper/MongoWrapperUtilTest.java
- added connection timeout and socket timeout environment variables substitution
- added unit test
=> [SP-3169][PDI-14643] mongoDB input does not accept variables

src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java, src/test/java/org/pentaho/mongo/wrapper/MongoWrapperUtilTest.java
* Added decryption for encrypted passwords
* Created test
=> [PDI-16022]-Test transformation fails with encrypted password in a parameter for "MongoDB Input" and "MongoDB Output" Steps

src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java, src/test/java/org/pentaho/mongo/wrapper/MongoWrapperUtilTest.java
Added decryption for encrypted passwords
=> [SP-3382]-[PDI-16022]-Test transformation fails with encrypted password in a parameter for "MongoDB Input" and "MongoDB Output" Steps

pom.xml
DO NOT MERGE prior to merge of kettle mavenization!
=> [BACKLOG-12977] GAV change for kettle-engine-test

src/main/java/org/pentaho/mongo/wrapper/field/MongodbInputDiscoverFieldsImpl.java, src/test/java/org/pentaho/mongo/wrapper/field/MongodbInputDiscoverFieldsImplTest.java
@pamval @mchen-len-son please review
=> [SP-3674] Backport of PDI-13205 - Min array index metadata for fields in MongoDB input getFields is sometimes incorrect (6.1 Suite)

pom.xml
=> [ENGOPS-3496] removed repository settings

src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInput.java, src/main/java/org/pentaho/mongo/wrapper/field/MongodbInputDiscoverFieldsImpl.java, src/test/java/org/pentaho/di/trans/steps/mongodbinput/BaseMongoDbStepTest.java, src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputTest.java, src/test/java/org/pentaho/mongo/wrapper/field/MongodbInputDiscoverFieldsImplTest.java
Reverts pentaho/pentaho-mongodb-plugin#165
=> Revert "[BACKLOG-22528] Changes aggregate function to use MongoDB cursors"

src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java
=> [BACKLOG-22749] Removed rogue ui element from the MongoDB Output Step in PDI

src/main/resources/OSGI-INF/blueprint/blueprint.xml
@kcruzada @pvale @jlien @pentaho-svigneri
Master PR: https://github.com/pentaho/pentaho-mongodb-plugin/pull/181
=> [BACKLOG-26373] Update and Validate In-Product Links

src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java, src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMeta.java
=> [BACKLOG-29422] Update and Validate In-Product Links in 8.3

src/main/resources/OSGI-INF/blueprint/blueprint.xml
=> [BACKLOG-29422] more updated doc links for 8.3

src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutput.java, src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputData.java, src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java, src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMeta.java, src/test/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDataTest.java, src/test/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputTest.java
Backport of:
#197
#194 
Last commit for some compatibility tests fixing.
**Do not squash commits on this one.**
Please merge also the other PR related to this same issue: https://github.com/pentaho/pentaho-kettle/pull/7385
@ssamora
=> [SP-5541][SP-5568] Backport of PDI-18466 - MongoDB output - Update all the array values in MongoDB based on a matching key (8.3 Suite)

src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInput.java, src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java, src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputTest.java
Two methods have reported code smell issues for cognitive complexity and it seemed like the previous pull request have also got the same and our assumption is  for some discussed reason, the developer(s) would have taken exception to go ahead and still commit the code and keeping the status-quo, we want to go ahead with this pull request and we would be creating a separate Jira to fix these issues and follow-up.
=> [PDI-19185] MongoDB input step clobbers rowset when "Execute for each row" on

pentaho-mongodb-plugin/src/main/resources/org/pentaho/di/trans/steps/mongodbinput/messages/messages_en_US.properties, pentaho-mongodb-plugin/src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMetaInjectionTest.java
=> [PDI-19451] Missing information for "allowDiskUse" property on MongoDB

pentaho-mongodb-plugin/pom.xml
=> [BACKLOG-36073] Fix dependency scope so all of kettle doesn't get added

pentaho-mongodb-plugin/src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java, pentaho-mongodb-plugin/src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMeta.java
[BACKLOG-36407] - Code to encrypt/decrypt connection string
=> [BACKLOG-36407] - Code to encrypt/decrypt connection string

assembly/plugin/pom.xml, pentaho-mongodb-plugin/pom.xml
[BACKLOG-36522]- removed dependent jars from this repo as they are present inside pentaho kettle
=> [BACKLOG-36522]- removed dependent jars from this repo as they are present

pentaho-mongodb-plugin/src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java, pentaho-mongodb-plugin/src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java
@smmribeiro 
@bcostahitachivantara 
@renato-s
=> [SP-6211] - Backport of PDI-19615 - Even no change in Mongo DB Input, Mongo DB Output steps asking PDI transformation to save (9.3 Suite)

pentaho-mongodb-plugin/pom.xml
[BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures
[BACKLOG-43935]: https://hv-eng.atlassian.net/browse/BACKLOG-43935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures
